# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalNoti', '0002_auto_20170622_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('apellido', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=70)),
                ('imagen', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
